//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClient.Services {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.MySportService")]
    public interface MySportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MySportService/GetScore", ReplyAction="http://tempuri.org/MySportService/GetScoreResponse")]
        int GetScore(string team);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MySportService/GetScore", ReplyAction="http://tempuri.org/MySportService/GetScoreResponse")]
        System.Threading.Tasks.Task<int> GetScoreAsync(string team);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MySportServiceChannel : WCFClient.Services.MySportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MySportServiceClient : System.ServiceModel.ClientBase<WCFClient.Services.MySportService>, WCFClient.Services.MySportService {
        
        public MySportServiceClient() {
        }
        
        public MySportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MySportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MySportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MySportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetScore(string team) {
            return base.Channel.GetScore(team);
        }
        
        public System.Threading.Tasks.Task<int> GetScoreAsync(string team) {
            return base.Channel.GetScoreAsync(team);
        }
    }
}
